import Image from "next/image";
import logoFull from "@/public/brand/logo.png";
import logoMark from "@/public/brand/logo-mark.png";
import { centre } from "@/lib/content";
import { cn } from "@/lib/utils";

/**
 * The centre's logo.
 *
 * Two lockups, both generated by scripts/build-logo.mjs from
 * "Logo Final Colour (Big).jpg":
 *
 *   mark  tree, sun and wordmark, tagline cropped off — for the header, where
 *         "WHERE DREAMS AND CREATIVITY MEET" would be an illegible smudge at 64px
 *   full  everything including the tagline, for the footer where there is room
 *
 * Imported statically rather than referenced by path so Next reads the real
 * width and height from the files at build time. They were hardcoded, and when
 * the mark was regenerated 14px taller the numbers silently disagreed with the
 * image — which is exactly the kind of thing that distorts a logo and nobody
 * notices for a month.
 *
 * ⚠️  Light backgrounds only. The sun carries a soft white-to-yellow halo that
 * cannot be keyed out without destroying it, so the transparent PNG still has
 * near-white pixels in that glow. Over white it is invisible; over anything dark
 * it shows as a pale blob with a ragged edge. Never place this on the video
 * headers — use text there.
 */
export function Logo({
  variant = "mark",
  className,
  priority = false,
}: {
  variant?: "mark" | "full";
  className?: string;
  priority?: boolean;
}) {
  return (
    <Image
      src={variant === "full" ? logoFull : logoMark}
      alt={`${centre.legalName} — ${centre.logoTagline}`}
      priority={priority}
      className={cn("w-auto", className)}
    />
  );
}
