import Image from "next/image";
import { centre } from "@/lib/content";
import { cn } from "@/lib/utils";

/**
 * The centre's logo.
 *
 * Two lockups, both generated by scripts/build-logo.mjs from
 * "Logo Final Colour (Big).jpg":
 *
 *   mark  tree, sun and wordmark, tagline cropped off — for the header, where
 *         "WHERE DREAMS AND CREATIVITY MEET" would be an illegible smudge at 44px
 *   full  everything including the tagline, for the footer where there is room
 *
 * ⚠️  Light backgrounds only. The sun carries a soft white-to-yellow halo that
 * cannot be keyed out without destroying it, so the transparent PNG still has
 * near-white pixels in that glow. Over white it is invisible; over anything dark
 * it shows as a pale blob with a ragged edge. Never place this on the video
 * headers — use text there.
 */
export function Logo({
  variant = "mark",
  className,
  priority = false,
}: {
  variant?: "mark" | "full";
  className?: string;
  priority?: boolean;
}) {
  const src = variant === "full" ? "/brand/logo" : "/brand/logo-mark";
  const dims =
    variant === "full"
      ? { width: 640, height: 388 }
      : { width: 520, height: 277 };

  return (
    <Image
      src={`${src}.png`}
      alt={`${centre.legalName} — ${centre.logoTagline}`}
      width={dims.width}
      height={dims.height}
      priority={priority}
      className={cn("w-auto", className)}
    />
  );
}
